In [87]:
import numpy as np
import pandas as pd
import tensorly as tl

### Simple graph

In [186]:
M_1 = np.array([
    [0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
])

M_2 = np.array([
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 1, 1, 0, 0],
])

k, l, m = 5, 5, 2

# T = np.array([M_1, M_2], dtype=np.float32).reshape(m, k, l)

T = np.array([M_1, M_2], dtype=np.float32).reshape(k, l, m)

ub = min(k * l, min(l * m, k * m))

In [187]:
T[:, :, 0]

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]], dtype=float32)

In [188]:
T[:, :, 1]

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [193]:
from tensorly.decomposition import parafac

pfs, X_parafac = parafac(T, rank=ub, n_iter_max=500, verbose=False, random_state=7)
# X_parafac = [np.around(i, decimals=4) for i in X_parafac]

In [194]:
pfs

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [195]:
print(X_parafac[0].shape) # U_1
print(X_parafac[1].shape) # U_2
print(X_parafac[2].shape) # U_3

(5, 10)
(5, 10)
(2, 10)


In [232]:
E = np.multiply(X_parafac[0], X_parafac[1])

In [239]:
np.round(np.dot(X_parafac[2][0], E.T), decimals=2)

array([0., 0., 0., 1., 0.], dtype=float32)

In [222]:
X_parafac[2][0] # loves

array([-0.94517255, -0.3603859 ,  0.31398666,  0.2731665 ,  0.45822367,
        0.29833233,  0.39250743, -0.05990679, -0.0134385 ,  0.53953254],
      dtype=float32)

In [221]:
X_parafac[1]

array([[ 0.27178967, -0.07063578, -0.74888265,  0.02127479,  1.2907367 ,
         0.41294888,  0.39496672, -0.16416723, -0.26346326, -0.6432519 ],
       [-0.09512821, -0.08523487, -3.8373191 ,  0.14993635, -0.91875684,
         1.2781788 ,  0.8743832 ,  0.49479288, -0.7882422 , -0.8614901 ],
       [-0.02646845,  0.6248567 , -8.788466  ,  0.8873296 ,  0.81691897,
        -0.15728754,  0.5748715 , -1.329028  ,  1.5095721 ,  1.1001946 ],
       [ 0.37883297,  0.1728949 ,  5.645493  ,  0.5123831 ,  8.267732  ,
         1.315223  ,  1.1517617 ,  1.0642756 , -0.6089525 , -1.4365882 ],
       [ 0.        ,  0.        ,  0.        , -0.        , -0.        ,
         0.        , -0.        ,  0.        , -0.        ,  0.        ]],
      dtype=float32)

In [235]:
np.dot(X_parafac[2][0].reshape(1, 10), E.T)

array([[8.9406967e-08, 3.2186508e-06, 2.7939677e-07, 1.0000024e+00,
        0.0000000e+00]], dtype=float32)

In [229]:
np.dot(X_parafac[2][1].reshape(1, 10), X_parafac[0].T)

array([[ 1.8361917 ,  1.2337005 ,  1.7607447 , -0.5765995 ,  0.03708496]],
      dtype=float32)

In [203]:
C = np.dot(X_parafac[0], X_parafac[2].T)
C

array([[ 3.0035686 ,  1.8361917 ],
       [ 0.5841738 ,  1.2337004 ],
       [ 2.7085853 ,  1.7607449 ],
       [-0.5210322 , -0.5765995 ],
       [-1.3144947 ,  0.03708493]], dtype=float32)

In [205]:
from sklearn.preprocessing import minmax_scale

minmax_scale(C, feature_range=(0, 1))

array([[1.        , 0.99999994],
       [0.43970373, 0.7502928 ],
       [0.9316862 , 0.9687305 ],
       [0.18375427, 0.        ],
       [0.        , 0.25434625]], dtype=float32)

In [30]:
np.matmul(A, B[2])

95.76726

In [26]:
[np.matmul(A, B[i]) for i in range(5)]

[35.346657, 49.68015, 95.76726, 187.42166, 281.37256]

In [ ]:
X_parafac

In [ ]:
X_pseudo = np.zeros((5,5))

In [ ]:
X_pseudo

In [ ]:
X_parafac[0][0].shape

In [ ]:
X_parafac[1].shape

In [ ]:
X_parafac[2].shape

In [ ]:
for i in range(10):
    
    X_pseudo += np.outer(np.outer(X_parafac[1][:,i], X_parafac[2][:,i]), X_parafac[0][0])

In [ ]:
np.outer(X_parafac[1][:,0], X_parafac[2][:,0])

In [ ]:
print(X_parafac[0]) # U_3
print(X_parafac[1]) # U_1
print(X_parafac[2]) # U_2

In [44]:
A = X_parafac[0][0].reshape(10, 1) # loves
# B = X_parafac[1][0].reshape(10, 1) # alex, object
B = X_parafac[2]

In [45]:
A

array([[-0.508017  ],
       [ 0.04855977],
       [-0.5267686 ],
       [-0.38346663],
       [-0.07712461],
       [ 0.5868502 ],
       [ 0.16851176],
       [ 0.48630828],
       [-0.6805024 ],
       [ 0.35819936]], dtype=float32)

In [46]:
B

array([[ 2.4175084e-01,  8.7845651e-03,  2.8193825e-01,  1.0258261e-03,
        -2.8163761e+01,  5.2582759e-02, -5.1577988e+00, -1.7518076e+00,
        -1.5863651e-02, -3.9530301e-01],
       [-4.5208868e-01, -6.3680804e-01,  8.4648684e-02, -3.9304371e-04,
         6.3493476e+00, -1.1339409e-02,  5.1487923e+00, -5.1417971e-01,
         1.3289965e-02, -1.1818472e-02],
       [-1.8897585e+00,  6.3560814e-01, -5.5325747e-01, -1.5251973e-03,
        -6.8427939e+00, -1.6718917e-02,  3.1315994e-02,  6.0610387e-02,
         8.3023690e-02,  1.0392955e-01],
       [ 2.1168585e-01, -5.4627854e-02, -2.0631940e+00, -3.7294507e-03,
        -9.1921844e+01,  2.6010234e-02,  9.7809173e-02, -3.3802733e+00,
         3.8194429e-02, -7.1877152e-01],
       [ 2.1168585e-01, -5.4627854e-02, -2.0631940e+00, -3.7294507e-03,
        -9.1921844e+01,  2.6010234e-02,  9.7809173e-02, -3.3802733e+00,
         3.8194429e-02, -7.1877152e-01]], dtype=float32)

In [47]:
C = np.dot(A, B)
C

ValueError: shapes (10,1) and (5,10) not aligned: 1 (dim 1) != 5 (dim 0)

In [ ]:
from sklearn.preprocessing import minmax_scale

minmax_scale(C, feature_range=(0, 1))

In [ ]:
X_parafac[0].T.shape

In [ ]:
X_parafac[1]

In [ ]:
X_parafac[0]

In [ ]:
A = X_parafac[0][0].reshape(1, 10) # loves
A

In [ ]:
X_parafac[1][0] # alex object

In [ ]:
B = X_parafac[1][0].reshape(1, 10).T # alex object.
B

In [ ]:
np.multiply(B, A)

In [ ]:
X_parafac[2][0] # alex subject

In [ ]:
np.multiply(X_parafac[0][0], X_parafac[1][0])

In [ ]:
print(X_parafac[0]) # U_3
print(X_parafac[1]) # U_1
print(X_parafac[2]) # U_2

In [ ]:
[np.sum(i) for i in X_parafac[1]]

In [ ]:
[np.sum(i) for i in X_parafac[2]]

In [ ]:
A = np.multiply(X_parafac[0][0], X_parafac[2])
A

In [ ]:
loves_p = np.sum(X_parafac[0][0])
loves_p

In [ ]:
objects = np.array([np.sum(i) for i in X_parafac[1]])
objects

In [ ]:
subjects = np.array([np.sum(i) for i in X_parafac[2]])
subjects

In [ ]:
objects * loves_p

In [ ]:
subjects * loves_p

In [ ]:
[np.sum(i) for i in A]

In [ ]:
X_parafac[1] * X_parafac[2]

In [ ]:
X_parafac[1] * X_parafac[2] * X_parafac[0][1]

### Group 1 (loves)

In [ ]:
X_parafac[0][0] * X_parafac[1]

In [ ]:
X_parafac[0][1] * X_parafac[1]

### Group 2 (hates)

In [ ]:
np.round(X_parafac[0][0] * X_parafac[2], decimals=4)

In [ ]:
np.around(X_parafac[0][1] * X_parafac[2], decimals=4)